### ISSUE TITLE
XUL: Deck element doesn't work properly with selectedIndex attribute.

### ISSUE THREAD

**Issue by andrey-square-pants** [clientside/amplesdk#110] opened 2011-11-28 19:07 UTC
XUL deck element doesn't work properly with selectedIndex attribute as
it is described at https://developer.mozilla.org/en/XUL_Tutorial/Stacks_and_Decks.

For example, this code

&lt;xul:deck selectedIndex="0"&gt;
&nbsp;&nbsp;&lt;xul:description&gt;Descr1&lt;/xul:description&gt;
&nbsp;&nbsp;&lt;xul:description&gt;Descr2&lt;/xul:description&gt;
&lt;/xul:deck&gt;

displays Descr1 and Descr2, whereas should display only Descr1.

**Comment by h6w** [comment] 2012-01-17 05:45
This particular problem appears to be caused by specifying an incorrect environment.   For example, I have reworked your code into a test case and specified the correct css attributes for the body tag here:
http://pastebin.com/A7ccN592

This shows only Descr1 as expected.

However, the selectedIndex appears to be ignored and the first child only displayed regardless.  I can force it by using ample.ready(), but this should not be required.  See here:  http://pastebin.com/diff.php?i=LRaitMK5

**Comment by ilinsky** [comment] 2012-02-22 13:21
Fixed in issue 126

**Closed as completed by ilinsky** 2012-02-22 13:21 UTC
Labels: module: xul
