### ISSUE TITLE
XUL: Dynamically adding to a toolbar causes a newline.

### ISSUE THREAD

**Issue by h6w** [clientside/amplesdk#88] opened 2011-10-07 15:55 UTC
If I have a XUL toolbar, e.g. 

<pre>
&lt;xul:toolbar id="toolbar1"&gt;
            &lt;xul:toolbarbutton id="button1" label="Button 1" command="cmd_button1" /&gt;
            &lt;xul:toolbarbutton id="button2" label="Button 2" command="cmd_button2" /&gt;
&lt;/xul:toolbar&gt;
</pre>

And I attempt to add another toolbar via ample.getElementById().appendChild() or ample.query().append(), e.g.

<pre>
var buttoncode = 
         '&lt;xul:toolbarbutton'
         +' xmlns:xul="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul"'
         +' id="button3"'
         +' label="Button 3"'
         +' command="cmd_button3"'
         +' /&gt;';             
ample.query("#toolbar1").append(buttoncode);
</pre>

Then the result is that the static buttons (the first two in the XUL) are on one line, whereas any buttons added dynamically are on a second line. e.g.
[Button 1]  [Button 2]
[Button 3]

This is tested in Chromium on Ubuntu.

**Comment by h6w** [comment] 2011-10-07 20:10
From the looks of the resulting HTML, it looks like a td element is being added to the toolbar div instead of the toolbar gateway.

**Comment by ilinsky** [comment] 2011-10-08 16:26
Added testcase https://github.com/clientside/amplesdk-tests/tree/master/manual/issues/088. 
DOM API works. jQuery API doesn't work.

**Comment by ilinsky** [comment] 2011-10-08 16:57
Closing issue, as the reported problem doesn't exist. Extending the use case, failures on appending button more than one time are caused by duplicate ids. Make ids unique.

**Closed as completed by ilinsky** 2011-10-08 16:57 UTC
