### ISSUE TITLE
xul:tree / xul-treebody--area scroll behaviour incorrect

### ISSUE THREAD

**Issue by CodaCodr** [clientside/amplesdk#25] opened 2010-11-01 11:29 UTC
Two problems:
1 - Mouse: only the scrollbar "thumb" appears to respond to the mouse; track, left/right/up/down buttons are ignored.
2 - Keyboard: no response at all that I can find.

I scraped this from Firebug:
div class="xul-treebody--area" style="height: 100%; width: 100%; overflow: scroll; position: relative;" onscroll="return ample.$instance(this)._onScroll(event)"

Tested in Firefox 3.6.2

**Comment by clientside** [comment] 2010-11-01 12:25
This may well be caused by Firebug stealing focus from the page. 
1) Please try closing Firebug. 
2) Try following practice fixing the problem with Firebug running: click in DOM view on some node then click on some area on the page. Then go to treev - now it should work.

**Comment by CodaCodr** [comment] 2010-11-01 12:35
Tested in a firefox profile without firebug installed, same problem.

**Comment by CodaCodr** [comment] 2010-11-01 12:36
And this really should not be "Closed" - surely?

**Comment by clientside** [comment] 2010-11-01 14:53
It should indeed not be closed. Probably I hit GitHub usability issue again.

**Comment by clientside** [comment] 2010-11-01 14:55
As described above, I bet you run into Firebug stealing focus issue (this usually happens when you start inspecting HTML in DOM tab). Please execute steps in suggestion "2" or open new tab with firebug disabled, load your page and test again. Then report that the issue is indeed gone!

**Comment by CodaCodr** [comment] 2010-11-01 15:35
As I said, I have a profile without firebug installed, the problem is still there.  But, just to show willing, I disabled firebug in my other profile where it is installed and retested: I would dearly love to report that the issue is gone, but it isn't gone - it persists! 

BTW, FF 4b6 does not have the issue.  Nor does IE7.

**Comment by clientside** [comment] 2010-11-01 15:48
Hm.. will look into the issue later this evening. BTW, Why do you run an older version of Firefox 3.6.2 - I am not sure I can get this version, as I run the most recent one which is 3.6.12

**Comment by CodaCodr** [comment] 2010-11-01 16:03
When I look at my help menu if FF I see "Resume downloading Firefox 3.6.3..." - when I click on it, nothing.  Similarly, AVG free would like me to upgrade, when I try, it crashes.

Need I mention that this is MS Vista? :)

I'll kill all my Firefoxes and get it up'd now.  Promise :)

**Comment by CodaCodr** [comment] 2010-11-01 16:22
3.6.12 installed, problem gone (both with and without firefox running).

thanks!

**Closed as completed** 2010-11-01 23:03 UTC
Labels: module: runtime, severity: major
